feat: track quick-start events
launchdarkly/ldcli pull request #205
Opened 2024-04-24 22:27 UTC by sunnyguduru

- **feat: Create an --output/-o flag for JSON or plain text responses (#195)**
- **feat: hardcoded resource cmds (#203)**
- **feat: output flag all commands (#201)**
- **added quickstart tracking**

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

2024-04-24 22:30 UTC, sunnyguduru commented on internal/quickstart/show_sdk_instructions.go
> +			"sdk": m.canonicalName,
canonicalName seems like the preferable one here as opposed to displayName.

2024-04-25 20:33 UTC, dbolson requested changes
I think we can use messages and do all the tracking in the container model. That way we don't need to pass the analytics tracker into the nested models, and we can keep the tracking calls closer together.

For example,
* when we start the tea program in `quickstart.go`, it calls the `createFlagModel#Init()`
* `createFlagModel#Init()` sends a `createFlagStartedMsg` with `time.Now()`
* container receives the message in `Update`
* container calls `SendSetupStartedEvent()` with its current step (1)
* when subsequent nested models are initialized, the send their own `{model}StartedMsg`
* the container receives those messages and calls `SendSetupStartedEvent()` as needed

It would be helpful to write up a plan for the message flow before changing the code to prevent more back-and-forth.

2024-04-25 20:34 UTC, sunnyguduru commented on internal/quickstart/choose_sdk.go
> +	m.analyticsTracker.SendSetupStartedEvent(m.accessToken, m.baseUri, viper.GetBool(cliflags.OutputFlag), "2 - sdk selection")
Dang, I made this mistake before. Thanks for catching it

2024-04-25 22:13 UTC, sunnyguduru commented
> I think we can use messages and do all the tracking in the container model. That way we don't need to pass the analytics tracker into the nested models, and we can keep the tracking calls closer together.
> 
> For example,
> 
> * when we start the tea program in `quickstart.go`, it calls the `createFlagModel#Init()`
> * `createFlagModel#Init()` sends a `createFlagStartedMsg` with `time.Now()`
> * container receives the message in `Update`
> * container calls `SendSetupStartedEvent()` with its current step (1)
> * when subsequent nested models are initialized, the send their own `{model}StartedMsg`
> * the container receives those messages and calls `SendSetupStartedEvent()` as needed
> 
> It would be helpful to write up a plan for the message flow before changing the code to prevent more back-and-forth.

### SendSetupStartedEvent

- when we start the tea program in `quickstart.go`, it calls the `createFlagModel#Init()`
- `createFlagModel#Init()` sends a `createFlagStartedMsg` with `time.Now()`
- container receives the message in `Update`
- container calls `SendSetupStartedEvent()` with its current step (1)
- when subsequent nested models are initialized, the send their own `{model}StartedMsg`
- the container receives those messages and calls `SendSetupStartedEvent()` as needed

### SendSetupSDKSelectedEvent

- the container receives `choseSDKMsg` with chosen SDK of type `string`. Then container calls `SendSetupSDKSelectedEvent` with the chosen SDK.

### SendSetupFlagToggledEvent

- the container receives `toggledFlagMsg` with endTime of type `time.Time` and count of type `int`. Then container calls `SendSetupFlagToggledEvent`.

2024-04-25 22:56 UTC, dbolson commented
Thinking about it more, the container shouldn't directly call the tracker but should send a command that does it, similar to the `toggleFlag` command. Something like
```
type eventTrackedMsg struct{}

func trackSetupStartedEvent(tracker analytics.Tracker, accessToken, baseURI string, optOut bool) tea.Cmd {
	return func() tea.Msg {
		tracker.SendWhateverEvent(accessToken, baseURI, optOut, time.Now())

		return eventTrackedMsg{}
	}
}
```
The container could use `tea.Batch()` or `tea.Sequence()` when setting `cmd` to get the current one plus the one to track the event.

2024-04-29 22:27 UTC, sunnyguduru commented
Closing to break into smaller PRS #215

2024-04-29 22:27 UTC, closed without merging